En este notebook, se utilizará una lista de empresas obtenidas desde TIKR y se realizará un muestreo aleatorio estratificado. Para ello, se abordarán los siguientes aspectos: 

- Discusión sobre los criterios para escoger los estratos. 
- Presentación rápida de los estratos y sus tamaños.
- Intervalo de confianza y definición del tamaño muestral para cada uno de los estratos.
- Selección de las empresas.

In [ ]:
import os

os.chdir("D:/Edelmin/Documentos/Estudios/TFM/portfolio-recsys-comparison/notebooks/0.1 Select sample.ipynb")

In [2]:
import pandas as pd

In [3]:
def gen_file_path(dir_data_path: str = 'path'):

    for file in os.listdir(dir_data_path):

        if 'LargeCaps' in file:
            yield dir_data_path + file
        else:
            continue

# Selección de datos para el sector de Bienes Raíces

In [76]:
path_gen = gen_file_path("data/02_intermediate/DatosSectores/")
path = next(path_gen)
df = pd.read_csv(path)

In [77]:
df.keys()

Index(['Símbolo', 'Empresa', 'Industria', 'Valor de mercado (US$B)', 'Sector',
       'Ubicación'],
      dtype='object')

Se quiere alcanzar un 95% de confianza en la representatividad de la muestra, con lo cual, debe tomarse un $z_{\alpha}$ de 1.96

In [4]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [6]:
df = catalog.load("CSV_LargeCaps_BienesRaices")

[03/01/26 18:40:53] INFO     Loading data from CSV_LargeCaps_BienesRaices (CSVDataset)...      ]8;id=743201;file://d:\Edelmin\Documentos\Estudios\TFM\portfolio-recsys-comparison\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=926892;file://d:\Edelmin\Documentos\Estudios\TFM\portfolio-recsys-comparison\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [20]:
sample = SampleData(df.shape[0])

In [22]:
sample.sample_size

27

In [78]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N}, en {path}")

El tamaño de la muestra será 26.16129973732853 de 28, en data/02_intermediate/DatosSectores/LargeCaps_BienesRaíces.csv

In [ ]:
import math

muestra = df.sample(n=math.ceil(n), random_state=42)

muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
9,MGR,Mirvac Group,Real Estate,"5,72",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
25,ICAD,Icade,Real Estate,"2,04",Fideicomisos de inversión inmobiliaria (REITs),Europe
8,CHC,Charter Hall Group,Real Estate,"5,94",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
21,GRT,Growthpoint Properties Limited,Real Estate,"2,54",Fideicomisos de inversión inmobiliaria (REITs),Africa / Middle East
0,WPC,W. P. Carey Inc.,Real Estate,"14,10",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
12,N2IU,Mapletree Pan Asia Commercial Trust,Real Estate,"5,02",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
17,8960,United Urban Investment Corporation,Real Estate,"3,35",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
22,ESBA,"Empire State Realty OP, L.P.",Real Estate,"2,30",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
11,FUNO 11,Fibra UNO,Real Estate,"5,21",Fideicomisos de inversión inmobiliaria (REITs),Latin America and Caribbean
13,3462,"Nomura Real Estate Master Fund, Inc.",Real Estate,"4,77",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
15,8984,Daiwa House REIT Investment Corporation,Real Estate,"3,85",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
1,SGP,Stockland,Real Estate,"8,76",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
4,LMP,LondonMetric Property Plc,Real Estate,"6,47",Fideicomisos de inversión inmobiliaria (REITs),Europe
5,EPRT,"Essential Properties Realty Trust, Inc.",Real Estate,"6,45",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
2,MRL,"MERLIN Properties SOCIMI, S.A.",Real Estate,"7,19",Fideicomisos de inversión inmobiliaria (REITs),Europe
16,KLCC,KLCC Property Holdings Berhad,Real Estate,"3,71",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
23,3309,"Sekisui House Reit, Inc.",Real Estate,"2,29",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
3,COV,Covivio,Real Estate,"6,67",Fideicomisos de inversión inmobiliaria (REITs),Europe
26,DANHOS 13,Fibra Danhos,Real Estate,"2,04",Fideicomisos de inversión inmobiliaria (REITs),Latin America and Caribbean
24,HR.UN,H&R Real Estate Investment Trust,Real Estate,"2,06",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
18,BNL,"Broadstone Net Lease, Inc.",Real Estate,"3,09",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
27,3279,Activia Properties Inc.,Real Estate,"2,03",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
20,T82U,Suntec Real Estate Investment Trust,Real Estate,"2,59",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
7,GPT,The GPT Group,Real Estate,"6,24",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
10,BLND,British Land Company PLC,Real Estate,"5,21",Fideicomisos de inversión inmobiliaria (REITs),Europe
14,8972,KDX Realty Investment Corporation,Real Estate,"4,42",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
19,ZRGYO,Ziraat Gayrimenkul Yatirim Ortakligi A.S.,Real Estate,"2,71",Fideicomisos de inversión inmobiliaria (REITs),Africa / Middle East

# Selección de datos para el sector de Consumo discrecional

In [80]:
path = next(path_gen)
df = pd.read_csv(path)

In [73]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,AMZN,"Amazon.com, Inc.",Consumer Discretionary,"2258,84",Minorista multilínea,United States and Canada
1,TSLA,"Tesla, Inc.",Consumer Discretionary,"1096,64",Automóviles,United States and Canada
2,HD,"The Home Depot, Inc.",Consumer Discretionary,"358,59",Minorista especializado,United States and Canada
3,BABA,Alibaba Group Holding Limited,Consumer Discretionary,"279,19",Minorista multilínea,United States and Canada
4,RMS,Hermès International Société en commandite par...,Consumer Discretionary,"277,23","Textiles, confecciones y artículos de lujo",Europe
...,...,...,...,...,...,...
612,500238,Whirlpool of India Limited,Consumer Discretionary,"2,03",Duraderos para el hogar,Asia / Pacific
613,6755,Fujitsu General Limited,Consumer Discretionary,"2,02",Duraderos para el hogar,Asia / Pacific
614,3918,NagaCorp Ltd.,Consumer Discretionary,"2,02","Hoteles, restaurantes y ocio",Asia / Pacific
615,1114,Brilliance China Automotive Holdings Limited,Consumer Discretionary,"2,02",Automóviles,Asia / Pacific
616,PMV,Premier Investments Limited,Consumer Discretionary,"2,01",Minorista especializado,Asia / Pacific

In [74]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 236.9888017917133 de 617 en data/02_intermediate/DatosSectores/LargeCaps_ConsumoDiscrecional.csv

In [75]:
import math
muestra = df.sample(n=math.ceil(n)+20 + 200, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=237)"] = opcionales

muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=237)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeConsumoDiscrecional.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=237)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeConsumoDiscrecional - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=237)
49,ADS,adidas AG,Consumer Discretionary,"41,31","Textiles, confecciones y artículos de lujo",Europe,No
581,ZO1,zooplus SE,Consumer Discretionary,"2,23",Minorista especializado,Europe,No
82,DRI,"Darden Restaurants, Inc.",Consumer Discretionary,"25,84","Hoteles, restaurantes y ocio",United States and Canada,No
304,GLBE,Global-E Online Ltd.,Consumer Discretionary,"5,49",Minorista multilínea,United States and Canada,No
109,6181,"Laopu Gold Co., Ltd.",Consumer Discretionary,"18,92","Textiles, confecciones y artículos de lujo",Asia / Pacific,No
...,...,...,...,...,...,...,...
462,RAIZ4,Raízen S.A.,Consumer Discretionary,"3,07",Minorista especializado,Latin America and Caribbean,Sí
506,000981,Sensteed Hi-Tech Group,Consumer Discretionary,"2,76",Componentes de automoción,Asia / Pacific,Sí
376,1808,HASEKO Corporation,Consumer Discretionary,"4,10",Duraderos para el hogar,Asia / Pacific,Sí
384,4190,Jarir Marketing Company,Consumer Discretionary,"3,96",Minorista especializado,Africa / Middle East,Sí
224,002920,"Huizhou Desay SV Automotive Co., Ltd.",Consumer Discretionary,"7,89",Componentes de automoción,Asia / Pacific,Sí

# Selección de datos para el sector de Energía

In [81]:
path = next(path_gen)
df = pd.read_csv(path)

In [44]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,2222,Saudi Arabian Oil Company,Energy,"1569,25","Petróleo, gas y combustibles consumibles",Africa / Middle East
1,XOM,Exxon Mobil Corporation,Energy,"466,83","Petróleo, gas y combustibles consumibles",United States and Canada
2,CVX,Chevron Corporation,Energy,"250,69","Petróleo, gas y combustibles consumibles",United States and Canada
3,857,PetroChina Company Limited,Energy,"220,28","Petróleo, gas y combustibles consumibles",Asia / Pacific
4,RELIANCE,Reliance Industries Limited,Energy,"214,53","Petróleo, gas y combustibles consumibles",Asia / Pacific
...,...,...,...,...,...,...
250,BKV,BKV Corporation,Energy,"2,06","Petróleo, gas y combustibles consumibles",United States and Canada
251,601975,Nanjing Tanker Corporation,Energy,"2,04","Petróleo, gas y combustibles consumibles",Asia / Pacific
252,EXX,Exxaro Resources Limited,Energy,"2,02","Petróleo, gas y combustibles consumibles",Africa / Middle East
253,DIALOG,Dialog Group Berhad,Energy,"2,02",Equipos y servicios energéticos,Asia / Pacific
254,MEDC,PT Medco Energi Internasional Tbk,Energy,"2,02","Petróleo, gas y combustibles consumibles",Asia / Pacific

In [14]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 153.50507709665285 de 255 en data/02_intermediate/DatosSectores/LargeCaps_Energia.csv

In [17]:
import math
muestra = df.sample(n=math.ceil(n)+20+70, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=154)"] = opcionales
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=154)
190,AEGISLOG,Aegis Logistics Limited,Energy,"3,22","Petróleo, gas y combustibles consumibles",Asia / Pacific,No
6,TTE,TotalEnergies SE,Energy,"134,97","Petróleo, gas y combustibles consumibles",Europe,No
79,PTTEP,PTT Exploration and Production Public Company ...,Energy,"13,50","Petróleo, gas y combustibles consumibles",Asia / Pacific,No
205,NOG,"Northern Oil and Gas, Inc.",Energy,"2,86","Petróleo, gas y combustibles consumibles",United States and Canada,No
117,APA,APA Corporation,Energy,"6,56","Petróleo, gas y combustibles consumibles",United States and Canada,No
...,...,...,...,...,...,...,...
116,OQEP,OQ Exploration and Production SAOG,Energy,"6,67","Petróleo, gas y combustibles consumibles",Africa / Middle East,Sí
87,TATN,PJSC Tatneft,Energy,"11,68","Petróleo, gas y combustibles consumibles",Europe,Sí
202,500109,Mangalore Refinery and Petrochemicals Limited,Energy,"2,89","Petróleo, gas y combustibles consumibles",Asia / Pacific,Sí
74,BPCL,Bharat Petroleum Corporation Limited,Energy,"16,12","Petróleo, gas y combustibles consumibles",Asia / Pacific,Sí
214,TVK,TerraVest Industries Inc.,Energy,"2,72",Equipos y servicios energéticos,United States and Canada,Sí

In [37]:
muestra.keys()

Index(['Símbolo', 'Empresa', 'Industria', 'Valor de mercado (US$B)', 'Sector',
       'Ubicación', 'Opcionales (n=154)'],
      dtype='object')

In [18]:
# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=154)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsEnergía.xlsx")

muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=154)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsEnergía - Extra.xlsx")

# Selección de datos para el sector Financiero

In [82]:
path = next(path_gen)
df = pd.read_csv(path)

In [20]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,VTI,Vanguard Index Funds - Vanguard Total Stock Ma...,Finanzas,"1839,26",Mercado de capitales,United States and Canada
1,VOO,Vanguard Index Funds - Vanguard S&P 500 ETF,Finanzas,"1584,11",Mercado de capitales,United States and Canada
2,BRK.A,Berkshire Hathaway Inc.,Finanzas,"1064,53",Servicios financieros diversificados,United States and Canada
3,JPM,JPMorgan Chase & Co.,Finanzas,"781,65",Bancos,United States and Canada
4,V,Visa Inc.,Finanzas,"658,31",Servicios financieros diversificados,United States and Canada
...,...,...,...,...,...,...
2050,SMLT,Samolet Group Public Joint Stock Company,Finanzas,"2,01",Gestión y desarrollo inmobiliario,Europe
2051,ANANDRATHI,Anand Rathi Wealth Limited,Finanzas,"2,01",Mercado de capitales,Asia / Pacific
2052,BFF,BFF Bank S.p.A.,Finanzas,"2,01",Servicios financieros diversificados,Europe
2053,MUNI,PIMCO ETF Trust - PIMCO Intermediate Municipal...,Finanzas,"2,00",Mercado de capitales,United States and Canada
2054,PXF,Invesco Exchange-Traded Fund Trust II - Invesc...,Finanzas,"2,00",Mercado de capitales,United States and Canada

In [21]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 323.78875873609604 de 2055 en data/02_intermediate/DatosSectores/LargeCaps_Financiero.csv

In [23]:
import math
muestra = df.sample(n=math.ceil(n)+20+500, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=324)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=324)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsFinanciero.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=324)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsFinanciero - Extra.xlsx")

muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=324)
1492,NMIH,"NMI Holdings, Inc.",Finanzas,"3,29",Servicios financieros diversificados,United States and Canada,No
543,SCHP,Schwab Strategic Trust - Schwab U.S. TIPS ETF,Finanzas,"12,87",Mercado de capitales,United States and Canada,No
1406,601099,"The Pacific Securities Co., Ltd",Finanzas,"3,58",Mercado de capitales,Asia / Pacific,No
861,FDN,First Trust Exchange-Traded Fund - First Trust...,Finanzas,"7,11",Mercado de capitales,United States and Canada,No
1128,3231,"Nomura Real Estate Holdings, Inc.",Finanzas,"5,02",Gestión y desarrollo inmobiliario,Asia / Pacific,No
...,...,...,...,...,...,...,...
105,PYPL,"PayPal Holdings, Inc.",Finanzas,"71,56",Servicios financieros diversificados,United States and Canada,Sí
126,VEU,Vanguard International Equity Index Funds - Va...,Finanzas,"63,56",Mercado de capitales,United States and Canada,Sí
944,VTBR,VTB Bank (public joint-stock company),Finanzas,"6,35",Bancos,Europe,Sí
1022,DXET,Xtrackers - Euro Stoxx 50 UCITS ETF,Finanzas,"5,75",Mercado de capitales,Europe,Sí
1165,PIPR,Piper Sandler Companies,Finanzas,"4,84",Mercado de capitales,United States and Canada,Sí

# Selección de datos para el sector de Industrial

In [83]:
path = next(path_gen)
df = pd.read_csv(path)

In [25]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,GE,General Electric Company,Industrials,"265,26",Aeroespacial y Defensa,United States and Canada
1,IHC,International Holding Company PJSC,Industrials,"238,16",Conglomerados industriales,Africa / Middle East
2,SIE,Siemens Aktiengesellschaft,Industrials,"194,13",Conglomerados industriales,Europe
3,UBER,"Uber Technologies, Inc.",Industrials,"191,66",Carretera y ferrocarril,United States and Canada
4,RTX,RTX Corporation,Industrials,"189,51",Aeroespacial y Defensa,United States and Canada
...,...,...,...,...,...,...
1079,HUBN,Huber+Suhner AG,Industrials,"2,00",Equipo eléctrico,Europe
1080,CHG,Chemring Group PLC,Industrials,"2,00",Aeroespacial y Defensa,Europe
1081,TGI,"Triumph Group, Inc.",Industrials,"2,00",Aeroespacial y Defensa,United States and Canada
1082,000089,"Shenzhen Airport Co., Ltd.",Industrials,"2,00",Infraestructura de transporte,Asia / Pacific
1083,8012,"Nagase & Co., Ltd.",Industrials,"2,00",Empresas comerciales y distribuidores,Asia / Pacific

In [26]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 283.83369230349786 de 1084 en data/02_intermediate/DatosSectores/LargeCaps_Industria.csv

In [27]:
import math
muestra = df.sample(n=math.ceil(n)+20 + 200, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=284)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=284)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsIndustria.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=284)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsIndustria - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=284)
693,EXPO,"Exponent, Inc.",Industrials,"3,84",Servicios profesionales,United States and Canada,No
56,DSV,DSV A/S,Industrials,"55,86",Transporte aéreo y logística,Europe,No
299,ALO,Alstom SA,Industrials,"10,63",Maquinaria,Europe,No
1027,HURN,Huron Consulting Group Inc.,Industrials,"2,15",Servicios profesionales,United States and Canada,No
208,KRX,Kingspan Group plc,Industrials,"15,16",Productos de construcción,Europe,No
...,...,...,...,...,...,...,...
433,A003670,"Posco Future M Co., Ltd.",Industrials,"7,38",Equipo eléctrico,Asia / Pacific,Sí
898,6139,"L&K Engineering Co., Ltd.",Industrials,"2,67",Servicios y suministros comerciales,Asia / Pacific,Sí
169,600018,"Shanghai International Port (Group) Co., Ltd.",Industrials,"18,96",Infraestructura de transporte,Asia / Pacific,Sí
757,601000,"TangShan Port Group Co.,Ltd",Industrials,"3,40",Infraestructura de transporte,Asia / Pacific,Sí
140,MTX,MTU Aero Engines AG,Industrials,"23,35",Aeroespacial y Defensa,Europe,Sí

# Selección de datos para el sector de Materiales

In [84]:
path = next(path_gen)
df = pd.read_csv(path)

In [48]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,LIN,Linde plc,Materials,"218,02",Productos quimicos,United States and Canada
1,BHP,BHP Group Limited,Materials,"120,32",Metales y Minería,Asia / Pacific
2,AI,L'Air Liquide S.A.,Materials,"118,10",Productos quimicos,Europe
3,RIO,Rio Tinto Group,Materials,"96,94",Metales y Minería,Europe
4,SHW,The Sherwin-Williams Company,Materials,"86,45",Productos quimicos,United States and Canada
...,...,...,...,...,...,...
544,ALLEI,Alleima AB (publ),Materials,"2,01",Metales y Minería,Europe
545,WPK,Winpak Ltd.,Materials,"2,01",Envases y Embalajes,United States and Canada
546,EIDPARRY,E.I.D.- Parry (India) Limited,Materials,"2,01",Productos quimicos,Asia / Pacific
547,QAMC,Qatar Aluminium Manufacturing Company Q.P.S.C.,Materials,"2,00",Metales y Minería,Africa / Middle East
548,5711,Mitsubishi Materials Corporation,Materials,"2,00",Metales y Minería,Asia / Pacific

In [49]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 226.25283213182286 de 549 en data/02_intermediate/DatosSectores/LargeCaps_MateriasPrimas.csv

In [50]:
import math
muestra = df.sample(n=math.ceil(n)+20+200, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=227)"] = opcionales

muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=227)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsMateriasPrimas.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=227)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsMateriasPrimas - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=227)
195,BSL,BlueScope Steel Limited,Materials,"6,40",Metales y Minería,Asia / Pacific,No
79,4091,Nippon Sanso Holdings Corporation,Materials,"15,87",Productos quimicos,Asia / Pacific,No
479,524200,Vinati Organics Limited,Materials,"2,35",Productos quimicos,Asia / Pacific,No
109,MOS,The Mosaic Company,Materials,"11,27",Productos quimicos,United States and Canada,No
473,4613,"Kansai Paint Co., Ltd.",Materials,"2,40",Productos quimicos,Asia / Pacific,No
...,...,...,...,...,...,...,...
326,300054,"Hubei Dinglong CO.,Ltd.",Materials,"3,69",Productos quimicos,Asia / Pacific,Sí
344,IVL,Indorama Ventures Public Company Limited,Materials,"3,51",Productos quimicos,Asia / Pacific,Sí
64,IFF,International Flavors & Fragrances Inc.,Materials,"19,11",Productos quimicos,United States and Canada,Sí
300,4021,Nissan Chemical Corporation,Materials,"4,00",Productos quimicos,Asia / Pacific,Sí
14,TPIA,PT Chandra Asri Pacific Tbk,Materials,"51,64",Productos quimicos,Asia / Pacific,Sí

# Selección de datos para el sector de Productos de primera necesidad

In [85]:
path = next(path_gen)
df = pd.read_csv(path)

In [33]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,WMT,Walmart Inc.,Consumer Staples,"782,63",Venta al por menor de alimentos y productos bá...,United States and Canada
1,COST,Costco Wholesale Corporation,Consumer Staples,"444,33",Venta al por menor de alimentos y productos bá...,United States and Canada
2,PG,The Procter & Gamble Company,Consumer Staples,"375,97",Productos domésticos,United States and Canada
3,KO,The Coca-Cola Company,Consumer Staples,"302,20",Bebidas,United States and Canada
4,PM,Philip Morris International Inc.,Consumer Staples,"287,16",Tabaco,United States and Canada
...,...,...,...,...,...,...
390,BELL,Bell Food Group AG,Consumer Staples,"2,03",Productos alimenticios,Europe
391,600872,Jonjee Hi-Tech Industrial and Commercial Holdi...,Consumer Staples,"2,03",Productos alimenticios,Asia / Pacific
392,4927,Pola Orbis Holdings Inc.,Consumer Staples,"2,02",Productos personales,Asia / Pacific
393,WMK,"Weis Markets, Inc.",Consumer Staples,"2,01",Venta al por menor de alimentos y productos bá...,United States and Canada
394,000998,"Yuan Long Ping High-Tech Agriculture Co., Ltd.",Consumer Staples,"2,01",Productos alimenticios,Asia / Pacific

In [34]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 195.00257016551862 de 395 en data/02_intermediate/DatosSectores/LargeCaps_ProductosDePrimeraNecesidad.csv

In [35]:
import math
muestra = df.sample(n=math.ceil(n)+20+170, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=196)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=196)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsProductosDePrimeraNecesidad.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=196)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsProductosDePrimeraNecesidad - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=196)
78,CARL B,Carlsberg A/S,Consumer Staples,"18,97",Bebidas,Europe,No
371,2050,Savola Group Company,Consumer Staples,"2,20",Productos alimenticios,Africa / Middle East,No
248,CWK,Cranswick plc,Consumer Staples,"3,85",Productos alimenticios,Europe,No
55,500790,Nestlé India Limited,Consumer Staples,"26,59",Productos alimenticios,Asia / Pacific,No
390,BELL,Bell Food Group AG,Consumer Staples,"2,03",Productos alimenticios,Europe,No
...,...,...,...,...,...,...,...
99,GODREJCP,Godrej Consumer Products Limited,Consumer Staples,"13,97",Productos personales,Asia / Pacific,Sí
372,KWS,KWS SAAT SE & Co. KGaA,Consumer Staples,"2,20",Productos alimenticios,Europe,Sí
87,HRL,Hormel Foods Corporation,Consumer Staples,"16,72",Productos alimenticios,United States and Canada,Sí
330,300146,"Byhealth Co., Ltd",Consumer Staples,"2,63",Productos personales,Asia / Pacific,Sí
214,CPIN,PT Charoen Pokphand Indonesia Tbk,Consumer Staples,"4,61",Productos alimenticios,Asia / Pacific,Sí

# Selección de datos para el sector de la Salud

In [86]:
path = next(path_gen)
df = pd.read_csv(path)

In [53]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,LLY,Eli Lilly and Company,Healthcare,"698,51",Productos farmacéuticos,United States and Canada
1,JNJ,Johnson & Johnson,Healthcare,"366,18",Productos farmacéuticos,United States and Canada
2,ABBV,AbbVie Inc.,Healthcare,"327,76",Biotecnología,United States and Canada
3,NOVO B,Novo Nordisk A/S,Healthcare,"313,05",Productos farmacéuticos,Europe
4,UNH,UnitedHealth Group Incorporated,Healthcare,"277,24",Proveedores y servicios de atención médica,United States and Canada
...,...,...,...,...,...,...
488,600529,Shandong Pharmaceutical Glass Co.Ltd,Healthcare,"2,06",Equipos y suministros sanitarios,Asia / Pacific
489,4530,"Hisamitsu Pharmaceutical Co., Inc.",Healthcare,"2,05",Productos farmacéuticos,Asia / Pacific
490,H02,Haw Par Corporation Limited,Healthcare,"2,04",Productos farmacéuticos,Asia / Pacific
491,002901,Double Medical Technology Inc.,Healthcare,"2,02",Equipos y suministros sanitarios,Asia / Pacific
492,853,MicroPort Scientific Corporation,Healthcare,"2,01",Equipos y suministros sanitarios,Asia / Pacific

In [54]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 216.16015339663983 de 493 en data/02_intermediate/DatosSectores/LargeCaps_Salud.csv

In [55]:
import math
muestra = df.sample(n=math.ceil(n)+20+200, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=217)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=217)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsSalud.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=217)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsSalud - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=217)
454,LGND,Ligand Pharmaceuticals Incorporated,Healthcare,"2,28",Productos farmacéuticos,United States and Canada,No
73,SIG,Sigma Healthcare Limited,Healthcare,"23,55",Proveedores y servicios de atención médica,Asia / Pacific,No
310,PTCT,"PTC Therapeutics, Inc.",Healthcare,"3,93",Biotecnología,United States and Canada,No
175,BBIO,"BridgeBio Pharma, Inc.",Healthcare,"8,44",Biotecnología,United States and Canada,No
332,7799,Heron Neutron Medical Corp.,Healthcare,"3,56",Equipos y suministros sanitarios,Asia / Pacific,No
...,...,...,...,...,...,...,...
315,MCOV B,Medicover AB (publ),Healthcare,"3,76",Proveedores y servicios de atención médica,Europe,Sí
88,PME,Pro Medicus Limited,Healthcare,"18,96",Tecnología para el cuidado de la salud,Asia / Pacific,Sí
387,PFIZER,Pfizer Limited,Healthcare,"2,96",Productos farmacéuticos,Asia / Pacific,Sí
273,EBO,EBOS Group Limited,Healthcare,"4,55",Proveedores y servicios de atención médica,Asia / Pacific,Sí
166,MASI,Masimo Corporation,Healthcare,"9,23",Equipos y suministros sanitarios,United States and Canada,Sí

# Selección de datos para el sector de Servicios

In [87]:
path = next(path_gen)
df = pd.read_csv(path)

In [57]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,NEE,"NextEra Energy, Inc.",Utilities,"146,99",Utilidades electricas,United States and Canada
1,IBE,"Iberdrola, S.A.",Utilities,"121,33",Utilidades electricas,Europe
2,TAQA,Abu Dhabi National Energy Company PJSC,Utilities,"107,46",Servicios públicos,Africa / Middle East
3,600900,"China Yangtze Power Co., Ltd.",Utilities,"104,33",Productores independientes de energía y electr...,Asia / Pacific
4,CEG,Constellation Energy Corporation,Utilities,"100,50",Utilidades electricas,United States and Canada
...,...,...,...,...,...,...
280,KEN,Kenon Holdings Ltd.,Utilities,"2,05",Productores independientes de energía y electr...,Africa / Middle East
281,INE,Innergex Renewable Energy Inc.,Utilities,"2,04",Productores independientes de energía y electr...,United States and Canada
282,MWC,"Manila Water Company, Inc.",Utilities,"2,03",Servicios de agua,Asia / Pacific
283,GRE,"Grenergy Renovables, S.A.",Utilities,"2,03",Productores independientes de energía y electr...,Europe
284,SAPR4,Companhia de Saneamento do Paraná - SANEPAR,Utilities,"2,00",Servicios de agua,Latin America and Caribbean

In [58]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 163.86135057471265 de 285 en data/02_intermediate/DatosSectores/LargeCaps_Servicios.csv

In [59]:
import math
muestra = df.sample(n=math.ceil(n)+20+100, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=167)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=167)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsServicios.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=167)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsServicios - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=167)
9,VST,Vistra Corp.,Utilities,"63,17",Productores independientes de energía y electr...,United States and Canada,No
249,REDE3,Rede Energia Participações S.A.,Utilities,"2,57",Utilidades electricas,Latin America and Caribbean,No
157,TXNM,"TXNM Energy, Inc.",Utilities,"5,24",Utilidades electricas,United States and Canada,No
209,MGEE,"MGE Energy, Inc.",Utilities,"3,33",Utilidades electricas,United States and Canada,No
75,SBSP3,Companhia de Saneamento Básico do Estado de Sã...,Utilities,"14,23",Servicios de agua,Latin America and Caribbean,No
...,...,...,...,...,...,...,...
20,DEWA,Dubai Electricity and Water Authority (PJSC),Utilities,"37,99",Servicios públicos,Africa / Middle East,Sí
188,BKH,Black Hills Corporation,Utilities,"4,12",Servicios públicos,United States and Canada,Sí
71,EVRG,"Evergy, Inc.",Utilities,"15,83",Utilidades electricas,United States and Canada,Sí
106,NHPC,NHPC Limited,Utilities,"9,99",Productores independientes de energía y electr...,Asia / Pacific,Sí
270,000966,"CHN Energy Changyuan Electric Power Co.,Ltd.",Utilities,"2,21",Productores independientes de energía y electr...,Asia / Pacific,Sí

# Selección de datos para el sector de Servicios de comunicación

In [88]:
path = next(path_gen)
df = pd.read_csv(path)

In [61]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,GOOGL,Alphabet Inc.,Communication Services,"2029,01",Servicios y medios interactivos,United States and Canada
1,META,"Meta Platforms, Inc.",Communication Services,"1790,70",Servicios y medios interactivos,United States and Canada
2,700,Tencent Holdings Limited,Communication Services,"589,07",Servicios y medios interactivos,Asia / Pacific
3,NFLX,"Netflix, Inc.",Communication Services,"544,35",Entretenimiento,United States and Canada
4,TMUS,"T-Mobile US, Inc.",Communication Services,"260,95",Servicios de telecomunicaciones inalámbricas,United States and Canada
...,...,...,...,...,...,...
292,TFI,TF1 SA,Communication Services,"2,11",Medios de comunicación,Europe
293,CCA,Cogeco Communications Inc.,Communication Services,"2,10",Servicios de telecomunicaciones diversificados,United States and Canada
294,2432,"DeNA Co., Ltd.",Communication Services,"2,09",Entretenimiento,Asia / Pacific
295,300182,"Beijing Jetsen Technology Co., Ltd",Communication Services,"2,00",Entretenimiento,Asia / Pacific
296,BLV,Believe S.A.,Communication Services,"2,00",Entretenimiento,Europe

In [62]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 167.74805928016934 de 297 en data/02_intermediate/DatosSectores/LargeCaps_ServiciosDeComunicacion.csv

In [63]:
import math
muestra = df.sample(n=math.ceil(n)+20 + 100, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=168)"] = opcionales

# muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=168)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsServiciosDeComunicación.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=168)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsServiciosDeComunicación - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=168)
167,MTNN,MTN Nigeria Communications PLC,Communication Services,"4,83",Servicios de telecomunicaciones inalámbricas,Africa / Middle East,No
211,GTM,ZoomInfo Technologies Inc.,Communication Services,"3,30",Servicios y medios interactivos,United States and Canada,No
63,VIVT3,Telefônica Brasil S.A.,Communication Services,"17,93",Servicios de telecomunicaciones diversificados,Latin America and Caribbean,No
154,002261,"Talkweb Information System Co.,Ltd.",Communication Services,"5,34",Entretenimiento,Asia / Pacific,No
5,941,China Mobile Limited,Communication Services,"243,64",Servicios de telecomunicaciones inalámbricas,Asia / Pacific,No
...,...,...,...,...,...,...,...
149,002558,"Giant Network Group Co., Ltd.",Communication Services,"5,59",Entretenimiento,Asia / Pacific,Sí
130,VENDA,Vend Marketplaces ASA,Communication Services,"7,48",Medios de comunicación,Europe,Sí
151,4751,"CyberAgent, Inc.",Communication Services,"5,54",Medios de comunicación,Asia / Pacific,Sí
99,TEL2 B,Tele2 AB (publ),Communication Services,"10,37",Servicios de telecomunicaciones inalámbricas,Europe,Sí
87,3045,"Taiwan Mobile Co., Ltd.",Communication Services,"11,54",Servicios de telecomunicaciones inalámbricas,Asia / Pacific,Sí

# Selección de datos para el sector de Tecnologías de la información

In [89]:
path = next(path_gen)
df = pd.read_csv(path)

In [90]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,MSFT,Microsoft Corporation,Information Technology,"3642,76",Software,United States and Canada
1,NVDA,NVIDIA Corporation,Information Technology,"3608,76",Semiconductores y equipos semiconductores,United States and Canada
2,AAPL,Apple Inc.,Information Technology,"2991,65","Tecnología Hardware, almacenamiento y periféricos",United States and Canada
3,AVGO,Broadcom Inc.,Information Technology,"1240,63",Semiconductores y equipos semiconductores,United States and Canada
4,2330,Taiwan Semiconductor Manufacturing Company Lim...,Information Technology,"923,34",Semiconductores y equipos semiconductores,Asia / Pacific
...,...,...,...,...,...,...
729,688502,MLOptic Corp.,Information Technology,"2,02","Equipos, instrumentos y componentes electrónicos",Asia / Pacific
730,4749,Advanced Echem Materials Company Limited,Information Technology,"2,02",Semiconductores y equipos semiconductores,Asia / Pacific
731,6976,"Taiyo Yuden Co., Ltd.",Information Technology,"2,01","Equipos, instrumentos y componentes electrónicos",Asia / Pacific
732,002373,"China Transinfo Technology Co., Ltd",Information Technology,"2,01",Servicios de IT,Asia / Pacific
733,002987,"Northking Information Technology Co., Ltd.",Information Technology,"2,00",Servicios de IT,Asia / Pacific

In [91]:
Z_alpha = 1.96

N = df.shape[0]

p = 0.5

q = 1-p

epsilon = 0.05

n = (N*p*q*(Z_alpha ** 2)) / ((epsilon**2)*(N-1)+p*q*(Z_alpha**2))

print(f"El tamaño de la muestra será {n} de {N} en {path}")

El tamaño de la muestra será 252.40201940635177 de 734 en data/02_intermediate/DatosSectores/LargeCaps_TecnologiasDeLaInformacion.csv

In [92]:
import math
muestra = df.sample(n=math.ceil(n)+20 + 200, random_state=42)


opcionales = []
for i in range(muestra.shape[0]):
    if i> (math.ceil(n)):
        opcionales.append("Sí")
    else: 
        opcionales.append("No")
muestra["Opcionales (n=253)"] = opcionales

muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=253)']].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsTecnologiasDeLaInformacion.xlsx")
muestra[['Símbolo', 'Empresa', 'Sector', 'Opcionales (n=253)']].iloc[math.ceil(n)+20:].to_excel("data/02_intermediate/MuestraEmpresasTikr/LargeCapsTecnologiasDeLaInformacion - Extra.xlsx")
muestra

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación,Opcionales (n=253)
559,4812,Dentsu Soken Inc.,Information Technology,"3,09",Servicios de IT,Asia / Pacific,No
33,ADI,"Analog Devices, Inc.",Information Technology,"116,61",Semiconductores y equipos semiconductores,United States and Canada,No
275,002236,"Zhejiang Dahua Technology Co., Ltd.",Information Technology,"7,15","Equipos, instrumentos y componentes electrónicos",Asia / Pacific,No
198,3034,Novatek Microelectronics Corp.,Information Technology,"10,90",Semiconductores y equipos semiconductores,Asia / Pacific,No
192,CIEN,Ciena Corporation,Information Technology,"11,22",Equipo de comunicaciones,United States and Canada,No
...,...,...,...,...,...,...,...
631,BB,BlackBerry Limited,Information Technology,"2,58",Software,United States and Canada,Sí
67,DDOG,"Datadog, Inc.",Information Technology,"45,18",Software,United States and Canada,Sí
497,CCC,Computacenter plc,Information Technology,"3,61",Servicios de IT,Europe,Sí
168,992,Lenovo Group Limited,Information Technology,"14,65","Tecnología Hardware, almacenamiento y periféricos",Asia / Pacific,Sí
444,002129,"TCL Zhonghuan Renewable Energy Technology Co.,...",Information Technology,"4,17",Semiconductores y equipos semiconductores,Asia / Pacific,Sí

# Modularización

In [ ]:
from pandas import DataFrame
from portfolio_recsys.pipelines.stratified_random_sampling.nodes import SampleData

df = catalog.load("CSV_LargeCaps_ConsumoDiscrecional")


def get_sample(dataframe: DataFrame, aditional_margin = 0) -> DataFrame:

    seed=42

    sample_info = SampleData(dataframe.shape[0])

    sample_size = sample_info.sample_size

    dataframe = dataframe.sample(n=sample_size + aditional_margin, random_state=seed)

    return dataframe

get_sample(df)

[03/01/26 19:25:45] INFO     Loading data from CSV_LargeCaps_ConsumoDiscrecional               ]8;id=764102;file://d:\Edelmin\Documentos\Estudios\TFM\portfolio-recsys-comparison\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=572455;file://d:\Edelmin\Documentos\Estudios\TFM\portfolio-recsys-comparison\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\
                             (CSVDataset)...

,Símbolo,Empresa,Industria,Valor de Mercado,Sector,Ubicación
49,ADS,adidas AG,Consumer Discretionary,"41,31 US$B","Textiles, confecciones y artículos de lujo",Europe
581,ZO1,zooplus SE,Consumer Discretionary,"2,23 US$B",Minorista especializado,Europe
82,DRI,"Darden Restaurants, Inc.",Consumer Discretionary,"25,84 US$B","Hoteles, restaurantes y ocio",United States and Canada
304,GLBE,Global-E Online Ltd.,Consumer Discretionary,"5,49 US$B",Minorista multilínea,United States and Canada
109,6181,"Laopu Gold Co., Ltd.",Consumer Discretionary,"18,92 US$B","Textiles, confecciones y artículos de lujo",Asia / Pacific
...,...,...,...,...,...,...
284,BBWI,"Bath & Body Works, Inc.",Consumer Discretionary,"6,08 US$B",Minorista especializado,United States and Canada
275,KALYANKJIL,Kalyan Jewellers India Limited,Consumer Discretionary,"6,25 US$B","Textiles, confecciones y artículos de lujo",Asia / Pacific
503,GENTING,Genting Berhad,Consumer Discretionary,"2,79 US$B","Hoteles, restaurantes y ocio",Asia / Pacific
69,LEN,Lennar Corporation,Consumer Discretionary,"29,30 US$B",Duraderos para el hogar,United States and Canada
264,LTH,"Life Time Group Holdings, Inc.",Consumer Discretionary,"6,52 US$B","Hoteles, restaurantes y ocio",United States and Canada