In [1]:
import os

os.chdir("C:/Users/Edelmín/Desktop/Estudios/Master y cursos universitarios/Inteligencia Artificial/Asignatura y apuntes/TFM/TFM/tfm_env")

# Reformateo de los datos

In [40]:
def market_value(string):

    if 'US$MM' in string:
        return str(float(string[:-6])/1000)

    if 'US$B' in string:
        return string[:-5]




import os

dir_path = 'data/02_intermediate/DatosSectoresExtraido/'
dest_dir_path = 'data/02_intermediate/DatosSectores/'

for file in os.listdir(dir_path):

    if file.endswith('.csv'):

        df = pd.read_csv(dir_path+file)
        print(file)
        df = df[df['Valor de Mercado'].apply(lambda x: str(x).lower() != 'nan')]

        if (df['Valor de Mercado'].apply(lambda x: ('US$B' in str(x))  or ('US$MM' in str(x))).sum() - df.shape[0])== 0:
            print("Valor de mercado en dólares americanos.")
                        
            df['Valor de Mercado'] = df['Valor de Mercado'].apply(market_value)

            df.rename(columns={"Valor de Mercado": "Valor de mercado (US$B)"}, inplace=True)

            df = df[['Símbolo', 'Empresa', 'Industria','Valor de mercado (US$B)', 'Sector', 
                'Ubicación']]
            df.to_csv(dest_dir_path+file, index=False)

        else:
            print("El dataframe no mide el valor de mercado en dólares americanos.")
            break
        
        print("Se terminó la comprobación satisfactoriamente.")

LargeCaps_BienesRaíces.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_ConsumoDiscrecional.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_Energia.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_Financiero.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_Industria.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_MateriasPrimas.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_ProductosDePrimeraNecesidad.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_Salud.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_Servicios.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_ServiciosDeComunicacion.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
LargeCaps_TecnologiasDeLaInformacion.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_BienesRaíces.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_ConsumoDiscrecional.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_Energia.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_Financiero.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_Industria.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_MateriasPrimas.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_ProductosDePrimeraNecesidad.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_Salud.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_Servicios.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_ServiciosDeComunicacion.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.
SmallCaps_TecnologiasDeLaInformacion.csv
Valor de mercado en dólares americanos.
Se terminó la comprobación satisfactoriamente.

In [41]:
df

,Símbolo,Empresa,Industria,Valor de mercado (US$B),Sector,Ubicación
0,DBD,"Diebold Nixdorf, Incorporated",Information Technology,"2,00","Tecnología Hardware, almacenamiento y periféricos",United States and Canada
1,002368,Taiji Computer Corporation Limited,Information Technology,"2,00",Servicios de IT,Asia / Pacific
2,600877,CETC Chips Technology Inc.,Information Technology,"2,00",Semiconductores y equipos semiconductores,Asia / Pacific
3,688522,"Naruida Technology Co., Ltd.",Information Technology,"1,98","Equipos, instrumentos y componentes electrónicos",Asia / Pacific
4,LAND,Landis+Gyr Group AG,Information Technology,"1,98","Equipos, instrumentos y componentes electrónicos",Europe
...,...,...,...,...,...,...
5397,AGTT,"Angstrom Technologies, Inc.",Information Technology,0.002,"Equipos, instrumentos y componentes electrónicos",United States and Canada
5398,MBO,MobilityOne Limited,Information Technology,0.002,Software,Europe
5399,CHWT.F,Coolpad Group Limited,Information Technology,0.002,"Tecnología Hardware, almacenamiento y periféricos",United States and Canada
5400,FKST,"Flowerkist Skin Care and Cosmetics, Inc.",Information Technology,0.002,"Tecnología Hardware, almacenamiento y periféricos",United States and Canada
5401,YTY,Wi2Wi Corporation,Information Technology,0.002,Equipo de comunicaciones,United States and Canada

# Extraer enlaces asociados a los tickers

In [42]:
import pandas as pd
import os
from bs4 import BeautifulSoup
import pandas as pd

def load_html(path='path.txt'):

    with open(path, "r", encoding='utf-8') as file:
        html = file.read()
    return html

def load_dataframe_from_csv(file):
    
    return pd.read_csv(file)


def get_href_related(soup="html_parser"):

    # Almacenar filas
    data = []

    # Recorrer cada fila de la tabla
    for tr in soup.find_all('tr'):
        tds = tr.find_all('td')
        
        if len(tds) >= 3:
            # Segundo <td> (índice 1) tiene el símbolo con el primer <a>
            symbol_tag = tds[1].find('a')
            symbol = symbol_tag.get_text(strip=True) if symbol_tag else ''
            href = symbol_tag['href'] if symbol_tag and symbol_tag.has_attr('href') else ''
            
            # Tercer <td> (índice 2) tiene el nombre de la empresa
            name_tag = tds[2].find('a')
            name = name_tag.get_text(strip=True) if name_tag else ''
            
            # Guardar la fila si el href empieza con /stock
            if href.startswith('/stock'):
                data.append({
                    'Símbolo': symbol,
                    'Empresa': name,
                    'Enlace': href
                })
    return pd.DataFrame(data)



def get_dataframe_with_href_from_txt(html_path):

    html = load_html(html_path)
    soup = BeautifulSoup(html, 'html.parser')

    df = get_href_related(soup)
    return df


# small_caps_path = "data/02_intermediate/DatosSectores/SmallCaps/"
# large_caps_path = "data/02_intermediate/DatosSectores/LargeCaps/"

# small_caps_file_paths = [small_caps_path + file for file in os.listdir(small_caps_path)]
# large_caps_file_paths = [large_caps_path + file for file in os.listdir(large_caps_path)]

# small_caps_file_names = [file[:-4] for file in os.listdir(small_caps_path)]
# large_caps_file_names = [file[:-4] for file in os.listdir(large_caps_path)]

file_path = "data/02_intermediate/DatosSectoresExtraido/"

file_names = [file[:-4] for file in os.listdir(file_path)]
csv_path_list = [file_path + file for file in os.listdir(file_path)]

In [43]:
pd.read_csv(csv_path_list[0])

,Símbolo,Empresa,Industria,Valor de Mercado,Sector,Ubicación
0,WPC,W. P. Carey Inc.,Real Estate,"14,10 US$B",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
1,SGP,Stockland,Real Estate,"8,76 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
2,MRL,"MERLIN Properties SOCIMI, S.A.",Real Estate,"7,19 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
3,COV,Covivio,Real Estate,"6,67 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
4,LMP,LondonMetric Property Plc,Real Estate,"6,47 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
5,EPRT,"Essential Properties Realty Trust, Inc.",Real Estate,"6,45 US$B",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
6,LAND,Land Securities Group Plc,Real Estate,"6,35 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
7,GPT,The GPT Group,Real Estate,"6,24 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
8,CHC,Charter Hall Group,Real Estate,"5,94 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
9,MGR,Mirvac Group,Real Estate,"5,72 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
10,BLND,British Land Company PLC,Real Estate,"5,21 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
11,FUNO 11,Fibra UNO,Real Estate,"5,21 US$B",Fideicomisos de inversión inmobiliaria (REITs),Latin America and Caribbean
12,N2IU,Mapletree Pan Asia Commercial Trust,Real Estate,"5,02 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
13,3462,"Nomura Real Estate Master Fund, Inc.",Real Estate,"4,77 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
14,8972,KDX Realty Investment Corporation,Real Estate,"4,42 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
15,8984,Daiwa House REIT Investment Corporation,Real Estate,"3,85 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
16,KLCC,KLCC Property Holdings Berhad,Real Estate,"3,71 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
17,8960,United Urban Investment Corporation,Real Estate,"3,35 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
18,BNL,"Broadstone Net Lease, Inc.",Real Estate,"3,09 US$B",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
19,ZRGYO,Ziraat Gayrimenkul Yatirim Ortakligi A.S.,Real Estate,"2,71 US$B",Fideicomisos de inversión inmobiliaria (REITs),Africa / Middle East
20,T82U,Suntec Real Estate Investment Trust,Real Estate,"2,59 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
21,GRT,Growthpoint Properties Limited,Real Estate,"2,54 US$B",Fideicomisos de inversión inmobiliaria (REITs),Africa / Middle East
22,ESBA,"Empire State Realty OP, L.P.",Real Estate,"2,30 US$B",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
23,3309,"Sekisui House Reit, Inc.",Real Estate,"2,29 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific
24,HR.UN,H&R Real Estate Investment Trust,Real Estate,"2,06 US$B",Fideicomisos de inversión inmobiliaria (REITs),United States and Canada
25,ICAD,Icade,Real Estate,"2,04 US$B",Fideicomisos de inversión inmobiliaria (REITs),Europe
26,DANHOS 13,Fibra Danhos,Real Estate,"2,04 US$B",Fideicomisos de inversión inmobiliaria (REITs),Latin America and Caribbean
27,3279,Activia Properties Inc.,Real Estate,"2,03 US$B",Fideicomisos de inversión inmobiliaria (REITs),Asia / Pacific

In [50]:
txt_dir_path = "data/01_raw/FicherosHtmlSectores/"

for csv_file, name_file in zip(csv_path_list, file_names):
    for txt_file in os.listdir(txt_dir_path):
        if name_file in txt_file:
            
            html_df = get_dataframe_with_href_from_txt(txt_dir_path + txt_file)
            html_df.set_index("Símbolo", inplace=True)
            html_df['Enlace'] = html_df['Enlace'].apply(lambda x: x.replace("about", "financials"))
            html_df['Enlace'] = html_df['Enlace'].apply(lambda x: x.replace("/stock", "https://app.tikr.com/stock"))

            break
    
    
    df = pd.read_csv(csv_file)
    df = df.join(html_df['Enlace'], on='Símbolo')
    
    df.to_csv("data/02_intermediate/DatosSectoresConHref/" + name_file + '.csv', index=False)

In [52]:
df

,Símbolo,Empresa,Industria,Valor de Mercado,Sector,Ubicación,Enlace
0,DBD,"Diebold Nixdorf, Incorporated",Information Technology,"2,00 US$B","Tecnología Hardware, almacenamiento y periféricos",United States and Canada,https://app.tikr.com/stock/financials?cid=2667...
1,002368,Taiji Computer Corporation Limited,Information Technology,"2,00 US$B",Servicios de IT,Asia / Pacific,https://app.tikr.com/stock/financials?cid=5408...
2,600877,CETC Chips Technology Inc.,Information Technology,"2,00 US$B",Semiconductores y equipos semiconductores,Asia / Pacific,https://app.tikr.com/stock/financials?cid=5524...
3,688522,"Naruida Technology Co., Ltd.",Information Technology,"1,98 US$B","Equipos, instrumentos y componentes electrónicos",Asia / Pacific,https://app.tikr.com/stock/financials?cid=6955...
4,LAND,Landis+Gyr Group AG,Information Technology,"1,98 US$B","Equipos, instrumentos y componentes electrónicos",Europe,https://app.tikr.com/stock/financials?cid=5875...
...,...,...,...,...,...,...,...
5397,AGTT,"Angstrom Technologies, Inc.",Information Technology,2 US$MM,"Equipos, instrumentos y componentes electrónicos",United States and Canada,https://app.tikr.com/stock/financials?cid=3923...
5398,MBO,MobilityOne Limited,Information Technology,2 US$MM,Software,Europe,https://app.tikr.com/stock/financials?cid=3541...
5399,CHWT.F,Coolpad Group Limited,Information Technology,2 US$MM,"Tecnología Hardware, almacenamiento y periféricos",United States and Canada,https://app.tikr.com/stock/financials?cid=1296...
5400,FKST,"Flowerkist Skin Care and Cosmetics, Inc.",Information Technology,2 US$MM,"Tecnología Hardware, almacenamiento y periféricos",United States and Canada,https://app.tikr.com/stock/financials?cid=2764...
5401,YTY,Wi2Wi Corporation,Information Technology,2 US$MM,Equipo de comunicaciones,United States and Canada,https://app.tikr.com/stock/financials?cid=2939...

Descarga los datos de la muestra

In [ ]:

def esperar(min_s=1.5, max_s=4.0):
    tiempo = random.uniform(min_s, max_s)
    print(f"Esperando {tiempo:.2f} segundos...")
    time.sleep(tiempo)

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from dotenv import load_dotenv
import time
import os
import pandas as pd

load_dotenv()
os.chdir("C:/Users/Edelmín/Desktop/Estudios/Master y cursos universitarios/Inteligencia Artificial/Asignatura y apuntes/TFM/TFM/tfm_env")
def session(headless=False):
        
    # Ruta al ejecutable de Brave
    brave_path = os.environ['PATH_BRAVE']  # Windows

    # Ruta a ChromeDriver (ajusta según tu sistema)
    chromedriver_path = os.environ['PATH_CHROMEDRIVER']

    options = Options()
    options.binary_location = brave_path

    options.add_argument(r"user-data-dir=C:/Users/Edelmín/AppData/Local/BraveSoftware/Brave-Browser/User Data")
    options.add_argument("profile-directory=Default")  # o "Profile 1", según corresponda


    # Configuración de descarga automática
    prefs = {
        "download.default_directory": os.environ['PATH_DOWNLOAD'],
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing.enabled": True
    }
    options.add_experimental_option("prefs", prefs)


    if headless:
        options.add_argument("--headless")  # Para correr sin ventana

    # Crea el servicio y el navegador
    service = Service(chromedriver_path)
    driver = webdriver.Chrome(service=service, options=options)

    return service, driver


def open_url(driver, url):
    driver.get(url)

def locate_window(driver):

    driver.set_window_position(-1920, 0)  # Ajusta 1920 si tu resolución cambia

    driver.maximize_window()


def login(driver):
    
    email = WebDriverWait(driver, 3).until(
    EC.visibility_of_element_located((By.ID, "input-13"))
    )
    
    email.send_keys(os.environ['TIKR_EMAIL'])

    contraseña = WebDriverWait(driver, 3).until(
    EC.visibility_of_element_located((By.ID, "input-16"))
    )
    
    contraseña.send_keys(os.environ['TIKR_PASSWORD'])


    login_boton = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, "button[data-v-0c6014fc]"))
    )
    login_boton.click()

    

    cerrar_boton = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[.//i[contains(@class, 'mdi-close')]]"))
    )
    cerrar_boton.click()


def load_href_list(dir):
    
    d = pd.DataFrame()
    ordered_list = []
    for file in os.listdir(dir):
        df = pd.read_csv(dir + file)
        ordered_list += [file for i in range(len(df))]
    d = pd.concat([d, df])
        
    return d.Enlace.tolist(), d['Símbolo'].tolist(), ordered_list

def open_dataset_source(driver):

    dataset = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((
    By.XPATH,
    "//div[@role='button' and @class='v-input__slot']"
    )))
    dataset.click()
    

def select_morningstar_source(driver):

    morningstar = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((
    By.XPATH,
    "//div[@role='option'][div/div[text()='Morningstar (Beta)']]"
    )))
    morningstar.click()
    

def open_export_selector(driver): 

    export_buttom = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((
    By.XPATH,
    "//div[@class='export-button']"
    )))
    export_buttom.click()





    
service, driver = session()
wait = WebDriverWait(driver, 10)

open_url(driver, "https://app.tikr.com/")
# locate_window(driver)
# login(driver)


href_list, company_list, file_list = load_href_list(os.environ['PATH_HREF'])
with open("data/01_raw/Descargas_incorrectas.txt", "a", encoding='utf-8') as errors,\
open("data/01_raw/Descargas correctas.txt", "a", encoding='utf-8') as corrects:
    
    errors.write("Enlace, Símbolo, Fichero\n")
    corrects.write("Enlace, Símbolo, Fichero\n")

for company_ref, company_ticker, file_container in zip(href_list, company_list, file_list):

    try:



        driver.get(company_ref)

        open_dataset_source(driver)
        select_morningstar_source(driver)
        open_export_selector(driver)
        
        
        statement_all = wait.until(EC.element_to_be_clickable((
        By.XPATH,
        "//legend[div[contains(normalize-space(.), 'Statement')]]/following-sibling::div//label[div[contains(normalize-space(.), 'All')]]")))
        statement_all.click()
        
        years_all = wait.until(EC.element_to_be_clickable((
        By.XPATH,
        "//legend[div[normalize-space(text())='Years']]/following-sibling::div//label[div[normalize-space(text())='All']]"
        )))
        years_all.click()
        
        
        export_buttom = wait.until(EC.element_to_be_clickable((
        By.CSS_SELECTOR,
        "button.btn-excel-download"
        )))
        export_buttom.click()
        with open("data/01_raw/Descargas correctas.txt", "a", encoding='utf-8') as corrects:
            corrects.write(f"{company_ref},{company_ticker},{file_container}\n")
        
    except Exception as e:
        with open("data/01_raw/Descargas_incorrectas.txt", "a", encoding='utf-8') as errors:
            errors.write(f"{company_ref},{company_ticker},{file_container}\n")
        continue

print('Terminé la ejecución.')

In [ ]:
import os
os.chdir("C:/Users/Edelmín/Desktop/Estudios/Master y cursos universitarios/Inteligencia Artificial/Asignatura y apuntes/TFM/TFM/tfm_env")

def session(headless=False):
        
    # Ruta al ejecutable de Brave
    brave_path = os.environ['PATH_BRAVE']  # Windows

    # Ruta a ChromeDriver (ajusta según tu sistema)
    chromedriver_path = os.environ['PATH_CHROMEDRIVER']

    options = Options()
    options.binary_location = brave_path

    options.add_argument(r"user-data-dir=C:/Users/Edelmín/AppData/Local/BraveSoftware/Brave-Browser/User Data")
    options.add_argument("profile-directory=Default")  # o "Profile 1", según corresponda


    # Configuración de descarga automática
    prefs = {
        "download.default_directory": os.environ['PATH_DOWNLOAD'],
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing.enabled": True
    }
    options.add_experimental_option("prefs", prefs)


    if headless:
        options.add_argument("--headless")  # Para correr sin ventana

    # Crea el servicio y el navegador
    service = Service(chromedriver_path)
    driver = webdriver.Chrome(service=service, options=options)

    return service, driver


service, driver = session()
wait = WebDriverWait(driver, 10)
open_url(driver, "https://app.tikr.com/")

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=138.0.7204.101)
Stacktrace:
	GetHandleVerifier [0x0x7ff649836f75+76917]
	GetHandleVerifier [0x0x7ff649836fd0+77008]
	(No symbol) [0x0x7ff6495e9dea]
	(No symbol) [0x0x7ff6495c2191]
	(No symbol) [0x0x7ff64966f83e]
	(No symbol) [0x0x7ff64968ff72]
	(No symbol) [0x0x7ff649668243]
	(No symbol) [0x0x7ff649631431]
	(No symbol) [0x0x7ff6496321c3]
	GetHandleVerifier [0x0x7ff649b0d2ad+3051437]
	GetHandleVerifier [0x0x7ff649b07903+3028483]
	GetHandleVerifier [0x0x7ff649b2589d+3151261]
	GetHandleVerifier [0x0x7ff64985183e+185662]
	GetHandleVerifier [0x0x7ff6498596ff+218111]
	GetHandleVerifier [0x0x7ff64983faf4+112628]
	GetHandleVerifier [0x0x7ff64983fca9+113065]
	GetHandleVerifier [0x0x7ff649826c78+10616]
	BaseThreadInitThunk [0x0x7ffdbad07374+20]
	RtlUserThreadStart [0x0x7ffdbb09cc91+33]

In [ ]:
# googl.to_csv('data/01_raw/GOOGL/price_historical.csv')

In [ ]:
import pandas as pd

pd.read_csv('data/01_raw/GOOGL/price_historical.csv', index_col='Date')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2004-08-19 00:00:00-04:00,2.487584,2.588579,2.387085,2.496041,893181924,0.0,0.0
2004-08-20 00:00:00-04:00,2.512708,2.713456,2.500021,2.694301,456686856,0.0,0.0
2004-08-23 00:00:00-04:00,2.754999,2.822910,2.712710,2.721417,365122512,0.0,0.0
2004-08-24 00:00:00-04:00,2.767188,2.776143,2.576390,2.608728,304946748,0.0,0.0
2004-08-25 00:00:00-04:00,2.610968,2.686591,2.584102,2.636839,183772044,0.0,0.0
...,...,...,...,...,...,...,...
2025-06-23 00:00:00-04:00,166.270004,167.339996,162.000000,165.190002,57671000,0.0,0.0
2025-06-24 00:00:00-04:00,166.919998,168.220001,166.130005,166.770004,40524300,0.0,0.0
2025-06-25 00:00:00-04:00,167.630005,172.360001,167.550003,170.679993,35479000,0.0,0.0
2025-06-26 00:00:00-04:00,172.429993,173.690002,169.940002,173.539993,31796700,0.0,0.0
2025-06-27 00:00:00-04:00,173.539993,178.679993,171.729996,178.529999,108022600,0.0,0.0

In [ ]:
import os

dir_path = 'data/02_intermediate/DatosSectoresExtraido/'

for file in os.listdir(dir_path):

    if file.endswith('.csv'):

        df = pd.read_csv(dir_path+file)
        print(file)
        df = df[df['Valor de Mercado'].apply(lambda x: str(x).lower() != 'nan')]

        if (df['Valor de Mercado'].apply(lambda x: ('US$B' in str(x))  or ('US$MM' in str(x))).sum() - df.shape[0])== 0:
            print("Valor de mercado en dólares americanos.")


        else:
            print("El dataframe no mide el valor de mercado en dólares americanos.")
            break

LargeCaps_BienesRaíces.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_ConsumoDiscrecional.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_Energia.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_Financiero.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_Industria.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_MateriasPrimas.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_ProductosDePrimeraNecesidad.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_Salud.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_Servicios.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_ServiciosDeComunicacion.txt.csv
Valor de mercado en dólares americanos.
LargeCaps_TecnologiasDeLaInformacion.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_BienesRaíces.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_ConsumoDiscrecional.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_Energia.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_Financiero.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_Industria.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_MateriasPrimas.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_ProductosDePrimeraNecesidad.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_Salud.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_Servicios.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_ServiciosDeComunicacion.txt.csv
Valor de mercado en dólares americanos.
SmallCaps_TecnologiasDeLaInformacion.txt.csv
Valor de mercado en dólares americanos.

In [ ]:
df[df.Símbolo == 'NA9']

,Unnamed: 0,Favorito,Símbolo,Empresa,Industria,Valor de Mercado,Sector,Ubicación
582,582,favorite_border,NA9,Nagarro SE,Information Technology,863 US$MM,Servicios de IT,Europe

In [ ]:
df.shape[0]

5402

In [ ]:
df[(df.Sector=='Servicios de IT') & (df['Ubicación']=='Europe')].shape[0]

188

In [ ]:
df.keys()

Index(['Unnamed: 0', 'Favorito', 'Símbolo', 'Empresa', 'Industria',
       'Valor de Mercado', 'Sector', 'Ubicación'],
      dtype='object')

In [ ]:
df

Preprocesamiento de los datos de los estados financieros

In [3]:
import os
import pandas as pd
os.chdir("C:/Users/Edelmín/Desktop/Estudios/Master y cursos universitarios/Inteligencia Artificial/Asignatura y apuntes/TFM/tfm_env")

In [6]:
LAND = pd.read_excel("data/01_raw/DatosEstadosFinancieros/TIKR - PLUS - Financials (31.3.06 - 31.3.25).xlsx", sheet_name=None)

In [13]:
LAND['Ratios'].set_index('Ratios | TIKR.com', inplace=True)

In [18]:
ratio_list = ["P/E Ratio", 'Net Income Margin %', 'Free Cash Flow Margin %', 'Sales Per Employee', 'Return on Invested Capital %', 'Return On Equity %', 'Return on Assets %']


LAND['Ratios'].loc[ratio_list]

,31/3/06,31/3/07,31/3/08,31/3/09,31/3/10,31/3/11,31/3/12,31/3/13,31/3/14,31/3/15,...,31/3/17,31/3/18,31/3/19,31/3/20,31/3/21,31/3/22,31/3/23,31/3/24,31/3/25,LTM
Ratios | TIKR.com,,,,,,,,,,,,,,,,,,,,,
P/E Ratio,NaN,NaN,"4,72x","7,69x","11,70x","9,44x",NaN,NaN,"13,03x","14,49x",...,"19,13x",NaN,NaN,"11,88x","18,52x","15,57x","11,85x",NaN,"15,61x","15,61x"
Net Income Margin %,-0.000805,0.021951,0.019263,0.018379,0.01883,0.032293,0.027378,0.034749,0.033064,0.040043,...,0.037961,0.038851,0.046036,0.043491,0.047437,0.05799,0.057724,0.052027,0.052194,NaN
Free Cash Flow Margin %,NaN,NaN,NaN,0.023734,NaN,NaN,NaN,0.026127,NaN,0.002307,...,0.017614,0.052986,0.020239,NaN,0.075236,NaN,NaN,0.107826,0.142857,NaN
Sales Per Employee,951938.235294,1219739.599384,1290737.082067,1064065.54878,1023993.948563,991055.172414,991093.637455,1087513.274336,1132265.524625,1159515.212982,...,1135360.613811,1126033.333333,893085.881588,1005955.668144,1038624.503311,1154736.20799,1178858.608894,1171211.578947,940786.266485,NaN
Return on Invested Capital %,-0.00202,0.061853,0.058759,0.064225,0.061136,0.103381,0.071153,0.104076,0.093513,0.109287,...,0.102538,0.106192,0.114781,0.11011,0.105657,0.135783,0.136163,0.118474,0.101983,NaN
Return On Equity %,-0.003997,0.126482,0.105582,0.075872,0.070813,0.116641,0.104646,0.149225,0.138585,0.167805,...,0.152095,0.153432,0.158603,0.151762,0.141904,0.172669,0.165427,0.137498,0.114907,NaN
Return on Assets %,-0.001418,0.043877,0.041009,0.034504,0.033125,0.058357,0.054911,0.078211,0.070373,0.081597,...,0.074435,0.073634,0.081979,0.081498,0.074926,0.094161,0.092487,0.075466,0.061034,NaN